# Numpy (Numerical Python)
## Numpy is a library to provide function to perform numerical analysis using arrays

In [2]:
# Importing numpy
import numpy as np

In [30]:
# Checking the numpy version
np.__version__

'1.13.1'

In [3]:
# np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
## object - set of data
## dtype - desired data type for the array (i1, i2, i4, f2, f4, f8)
## copy - object is copied
## order - memory layout (row or column based)

# np.dtype(object, align, copy)
## boolean, integer, floating-point, timedelta, datetime, unicode and many more

In [65]:
arr = np.array([[5,10],[15,20]], dtype = int)
arr

array([[ 5, 10],
       [15, 20]])

In [56]:
# Type of the array
type(arr)

numpy.ndarray

In [15]:
dt = np.dtype([('name', 'S10'), ('marks', float), ('age', 'i1')])
dt

data = np.array([('a', 100, 20), ('b', 90, 30), ('c', 75, 18)], dtype = dt) # Array of tuples
data

array([(b'a',  100., 20), (b'b',   90., 30), (b'c',   75., 18)],
      dtype=[('name', 'S10'), ('marks', '<f8'), ('age', 'i1')])

In [17]:
# Shape of the array
data.shape
# Dimension of the array
data.ndim

1

In [22]:
# Modifying the array
arr.shape = (2, 2)
arr.shape
arr

array([[ 5, 10],
       [15, 20]])

In [28]:
# Reshaping the array
arr = arr.reshape(2,2)
arr

array([[ 5, 10],
       [15, 20]])

In [29]:
arr.dtype

dtype('int32')

In [31]:
# arange function
x = np.arange(5, 50, 5, 'i1')
x

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45], dtype=int8)

In [38]:
arr = np.array(x)
arr = arr.reshape(3,3)
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]], dtype=int8)

In [39]:
# Useful functions
## np.empty(shape, dtype, order) # random vars
## np.zeros(shape, dtype, order)
## np.ones()
## np.asarray(a, dtype = None, order = None)
## np.frombuffer()
## np.arange(start, stop, step, dtype)

In [40]:
empty = np.empty((2, 3), dtype = 'i2')
empty

array([[3, 0, 0],
       [0, 3, 0]], dtype=int16)

In [41]:
zero = np.zeros((2,2), dtype = 'i2')
zero

array([[0, 0],
       [0, 0]], dtype=int16)

In [44]:
ones = np.ones((2, 2), dtype = 'float')
ones

array([[ 1.,  1.],
       [ 1.,  1.]])

In [45]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
y = 2 * (x**2) + 5
y

array([  7,  13,  23,  37,  55,  77, 103, 133, 167, 205], dtype=int32)

In [53]:
matrix = np.array([x, y])
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  7,  13,  23,  37,  55,  77, 103, 133, 167, 205]])

In [54]:
matrix = np.transpose(matrix)
matrix

array([[  1,   7],
       [  2,  13],
       [  3,  23],
       [  4,  37],
       [  5,  55],
       [  6,  77],
       [  7, 103],
       [  8, 133],
       [  9, 167],
       [ 10, 205]])

In [68]:
# Equally spaced values between two points
x = np.linspace(1, 10, num = 50)
x

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [75]:
samples, spacing = np.linspace(1, 10, num = 5, retstep = True)
print('Sample: ', samples)
print('Spacing: ', spacing)

Sample:  [  1.     3.25   5.5    7.75  10.  ]
Spacing:  2.25
